### ISSUE TITLE
exclude_fromheader_domains is case sensitive

### ISSUE THREAD

**Issue by andreasschulze** [mail-de/mailheadercheck#6]
- given 5322.From: `from@Example.Org`
- given config.yml
```
dry_run: 0
checks:
  missing_messageid_header:
    exclude_fromheader_domains:
      - example.org
```

this still block a message without `Message-ID`-Header. I have to explicit set `- Example.Org`
is this intended?
