### ISSUE TITLE
exclude_envelopefrom_domains don't work

### ISSUE THREAD

**Issue by andreasschulze** [mail-de/mailheadercheck#7]
given 5321.MailFrom: `MAIL FROM:<sender@example.org>`
given config.yml
```
dry_run: 0
checks:
  missing_messageid_header:
    exclude_envelopefrom_domains:
      - example.org
```
this still block a message without Message-ID-Header. I have to explicit set `- example.org>`

(my?) postfix-3.8.5 send the envelope sender including `<` and `>`
The code does not handle these additional characters.
